-- =============================================================================
-- DDL: SNOWFLAKE_SUMMIT_2026_HOL_DB.SF_HOL_2026_RETAIL
-- =============================================================================
-- Complete schema definition for The Build Depot (TBD) retail demo database.
-- This file is DDL-only: no DML (INSERT/UPDATE/DELETE/MERGE).
--
-- Run this file first on a clean database, then run the DML file to populate data.
--
-- Generated from live schema via GET_DDL() on 2026-05-15, with constraints
-- added from the design specification.
-- =============================================================================

CREATE DATABASE IF NOT EXISTS SNOWFLAKE_SUMMIT_2026_HOL_DB;
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_SUMMIT_2026_HOL_DB.SF_HOL_2026_RETAIL;

USE SCHEMA SNOWFLAKE_SUMMIT_2026_HOL_DB.SF_HOL_2026_RETAIL;

-- #############################################################################
-- TABLES
-- #############################################################################

-- -----------------------------------------------------------------------------
-- Reference / Lookup Tables
-- -----------------------------------------------------------------------------

CREATE OR REPLACE TABLE RET_WAREHOUSES (
    CTID_FIVETRAN_ID  VARCHAR(16777216) NOT NULL,
    ID                NUMBER(38,0),
    NAME              VARCHAR(100),
    ADDRESS           VARCHAR(200),
    CITY              VARCHAR(100),
    STATE             VARCHAR(2),
    ZIP               VARCHAR(10),
    CAPACITY_SQFT     NUMBER(10,0),
    IS_ACTIVE         BOOLEAN,
    CREATED_AT        TIMESTAMP_NTZ(9),
    _FIVETRAN_DELETED BOOLEAN,
    _FIVETRAN_SYNCED  TIMESTAMP_TZ(9),
    PRIMARY KEY (CTID_FIVETRAN_ID),
    CONSTRAINT UQ_WAREHOUSES_ID UNIQUE (ID)
);

CREATE OR REPLACE TABLE RET_PRODUCT_CATEGORIES (
    CTID_FIVETRAN_ID  VARCHAR(16777216) NOT NULL,
    ID                NUMBER(38,0),
    NAME              VARCHAR(100),
    DESCRIPTION       VARCHAR(500),
    CREATED_AT        TIMESTAMP_NTZ(9),
    UPDATED_AT        TIMESTAMP_NTZ(9),
    _FIVETRAN_DELETED BOOLEAN,
    _FIVETRAN_SYNCED  TIMESTAMP_TZ(9),
    PRIMARY KEY (CTID_FIVETRAN_ID),
    CONSTRAINT UQ_PRODUCT_CATEGORIES_ID UNIQUE (ID)
);

CREATE OR REPLACE TABLE RET_PRODUCT_SUBCATEGORIES (
    CTID_FIVETRAN_ID  VARCHAR(16777216) NOT NULL,
    ID                NUMBER(38,0),
    CATEGORY_ID       NUMBER(38,0),
    NAME              VARCHAR(100),
    DESCRIPTION       VARCHAR(500),
    CREATED_AT        TIMESTAMP_NTZ(9),
    UPDATED_AT        TIMESTAMP_NTZ(9),
    _FIVETRAN_DELETED BOOLEAN,
    _FIVETRAN_SYNCED  TIMESTAMP_TZ(9),
    PRIMARY KEY (CTID_FIVETRAN_ID),
    CONSTRAINT UQ_PRODUCT_SUBCATEGORIES_ID UNIQUE (ID)
);

CREATE OR REPLACE TABLE RET_VENDORS (
    CTID_FIVETRAN_ID  VARCHAR(16777216) NOT NULL,
    ID                NUMBER(38,0),
    NAME              VARCHAR(200),
    CONTACT_EMAIL     VARCHAR(300),
    CITY              VARCHAR(100),
    STATE             VARCHAR(2),
    CREATED_AT        TIMESTAMP_NTZ(9),
    _FIVETRAN_DELETED BOOLEAN,
    _FIVETRAN_SYNCED  TIMESTAMP_TZ(9),
    DEMO_BATCH_ID     VARCHAR(50),
    PRIMARY KEY (CTID_FIVETRAN_ID),
    CONSTRAINT UQ_VENDORS_ID UNIQUE (ID)
);

-- -----------------------------------------------------------------------------
-- Core Entity Tables
-- -----------------------------------------------------------------------------

CREATE OR REPLACE TABLE RET_CUSTOMERS (
    CTID_FIVETRAN_ID  VARCHAR(16777216) NOT NULL,
    ID                NUMBER(38,0),
    FIRST_NAME        VARCHAR(100),
    LAST_NAME         VARCHAR(100),
    EMAIL             VARCHAR(300),
    PHONE             VARCHAR(20),
    ADDRESS           VARCHAR(200),
    CITY              VARCHAR(100),
    STATE             VARCHAR(2),
    ZIP               VARCHAR(10),
    REGION            VARCHAR(50),
    CUSTOMER_TYPE     VARCHAR(20),
    CREATED_AT        TIMESTAMP_NTZ(9),
    UPDATED_AT        TIMESTAMP_NTZ(9),
    _FIVETRAN_DELETED BOOLEAN,
    _FIVETRAN_SYNCED  TIMESTAMP_TZ(9),
    PRIMARY KEY (CTID_FIVETRAN_ID),
    CONSTRAINT UQ_CUSTOMERS_ID UNIQUE (ID)
);

CREATE OR REPLACE TABLE RET_PRODUCTS (
    CTID_FIVETRAN_ID  VARCHAR(16777216) NOT NULL,
    ID                NUMBER(38,0),
    SKU               VARCHAR(20),
    NAME              VARCHAR(200),
    DESCRIPTION       VARCHAR(1000),
    SUBCATEGORY_ID    NUMBER(38,0),
    BRAND             VARCHAR(100),
    UNIT_PRICE        NUMBER(10,2),
    WEIGHT_LBS        NUMBER(8,2),
    IS_ACTIVE         BOOLEAN,
    CREATED_AT        TIMESTAMP_NTZ(9),
    UPDATED_AT        TIMESTAMP_NTZ(9),
    _FIVETRAN_DELETED BOOLEAN,
    _FIVETRAN_SYNCED  TIMESTAMP_TZ(9),
    DEMO_BATCH_ID     VARCHAR(50),
    VENDOR_ID         NUMBER(38,0),
    PRIMARY KEY (CTID_FIVETRAN_ID),
    CONSTRAINT UQ_PRODUCTS_ID UNIQUE (ID)
);

-- -----------------------------------------------------------------------------
-- Transaction Tables
-- -----------------------------------------------------------------------------

CREATE OR REPLACE TABLE RET_ORDERS (
    CTID_FIVETRAN_ID  VARCHAR(16777216) NOT NULL,
    ID                NUMBER(38,0),
    CUSTOMER_ID       NUMBER(38,0),
    ORDER_DATE        TIMESTAMP_NTZ(9),
    STATUS            VARCHAR(20),
    SHIPPING_METHOD   VARCHAR(30),
    SHIPPING_ADDRESS  VARCHAR(200),
    SHIPPING_CITY     VARCHAR(100),
    SHIPPING_STATE    VARCHAR(2),
    SHIPPING_ZIP      VARCHAR(10),
    SUBTOTAL          NUMBER(10,2),
    TAX_AMOUNT        NUMBER(10,2),
    SHIPPING_COST     NUMBER(10,2),
    TOTAL_AMOUNT      NUMBER(10,2),
    CREATED_AT        TIMESTAMP_NTZ(9),
    UPDATED_AT        TIMESTAMP_NTZ(9),
    _FIVETRAN_DELETED BOOLEAN,
    _FIVETRAN_SYNCED  TIMESTAMP_TZ(9),
    WAREHOUSE_ID      NUMBER(38,0),
    DEMO_BATCH_ID     VARCHAR(50),
    PRIMARY KEY (CTID_FIVETRAN_ID),
    CONSTRAINT UQ_ORDERS_ID UNIQUE (ID)
);

CREATE OR REPLACE TABLE RET_ORDER_ITEMS (
    CTID_FIVETRAN_ID  VARCHAR(16777216) NOT NULL,
    ID                NUMBER(38,0),
    ORDER_ID          NUMBER(38,0),
    PRODUCT_ID        NUMBER(38,0),
    QUANTITY          NUMBER(10,0),
    UNIT_PRICE        NUMBER(10,2),
    DISCOUNT_PCT      NUMBER(5,2),
    LINE_TOTAL        NUMBER(10,2),
    CREATED_AT        TIMESTAMP_NTZ(9),
    _FIVETRAN_DELETED BOOLEAN,
    _FIVETRAN_SYNCED  TIMESTAMP_TZ(9),
    DEMO_BATCH_ID     VARCHAR(50),
    PRIMARY KEY (CTID_FIVETRAN_ID),
    CONSTRAINT UQ_ORDER_ITEMS_ID UNIQUE (ID)
);

CREATE OR REPLACE TABLE RET_RETURNS (
    CTID_FIVETRAN_ID  VARCHAR(16777216) NOT NULL,
    ID                NUMBER(38,0),
    ORDER_ID          NUMBER(38,0),
    ORDER_ITEM_ID     NUMBER(38,0),
    PRODUCT_ID        NUMBER(38,0),
    CUSTOMER_ID       NUMBER(38,0),
    RETURN_DATE       DATE,
    QUANTITY          NUMBER(10,0),
    RETURN_REASON     VARCHAR(50),
    NOTES             VARCHAR(500),
    CREATED_AT        TIMESTAMP_NTZ(9),
    _FIVETRAN_DELETED BOOLEAN,
    _FIVETRAN_SYNCED  TIMESTAMP_TZ(9),
    DEMO_BATCH_ID     VARCHAR(50),
    PRIMARY KEY (CTID_FIVETRAN_ID)
);

CREATE OR REPLACE TABLE RET_SHIPMENTS (
    CTID_FIVETRAN_ID         VARCHAR(16777216) NOT NULL,
    ID                       NUMBER(38,0),
    DESTINATION_WAREHOUSE_ID NUMBER(38,0),
    ORIGIN_WAREHOUSE_ID      NUMBER(38,0),
    SHIPMENT_DATE            DATE,
    STATUS                   VARCHAR(20),
    NOTES                    VARCHAR(500),
    CREATED_AT               TIMESTAMP_NTZ(9),
    _FIVETRAN_DELETED        BOOLEAN,
    _FIVETRAN_SYNCED         TIMESTAMP_TZ(9),
    DEMO_BATCH_ID            VARCHAR(50),
    PRIMARY KEY (CTID_FIVETRAN_ID),
    CONSTRAINT UQ_SHIPMENTS_ID UNIQUE (ID)
);

CREATE OR REPLACE TABLE RET_SHIPMENT_LINES (
    CTID_FIVETRAN_ID  VARCHAR(16777216) NOT NULL,
    ID                NUMBER(38,0),
    SHIPMENT_ID       NUMBER(38,0),
    PRODUCT_ID        NUMBER(38,0),
    QUANTITY          NUMBER(10,0),
    CREATED_AT        TIMESTAMP_NTZ(9),
    _FIVETRAN_DELETED BOOLEAN,
    _FIVETRAN_SYNCED  TIMESTAMP_TZ(9),
    DEMO_BATCH_ID     VARCHAR(50),
    PRIMARY KEY (CTID_FIVETRAN_ID)
);

-- -----------------------------------------------------------------------------
-- Inventory Tables
-- -----------------------------------------------------------------------------

CREATE OR REPLACE TABLE RET_INVENTORY (
    CTID_FIVETRAN_ID  VARCHAR(16777216) NOT NULL,
    ID                NUMBER(38,0),
    PRODUCT_ID        NUMBER(38,0),
    WAREHOUSE_ID      NUMBER(38,0),
    QUANTITY_ON_HAND  NUMBER(10,0),
    REORDER_POINT     NUMBER(10,0),
    REORDER_QUANTITY  NUMBER(10,0),
    LAST_RESTOCKED_AT TIMESTAMP_NTZ(9),
    UPDATED_AT        TIMESTAMP_NTZ(9),
    _FIVETRAN_DELETED BOOLEAN,
    _FIVETRAN_SYNCED  TIMESTAMP_TZ(9),
    DEMO_BATCH_ID     VARCHAR(50),
    PRIMARY KEY (CTID_FIVETRAN_ID)
);

CREATE OR REPLACE TABLE RET_INVENTORY_TRANSACTIONS (
    CTID_FIVETRAN_ID  VARCHAR(16777216) NOT NULL,
    ID                NUMBER(38,0),
    PRODUCT_ID        NUMBER(38,0),
    WAREHOUSE_ID      NUMBER(38,0),
    TRANSACTION_TYPE  VARCHAR(20),
    QUANTITY          NUMBER(10,0),
    REFERENCE_ID      NUMBER(38,0),
    NOTES             VARCHAR(500),
    CREATED_AT        TIMESTAMP_NTZ(9),
    _FIVETRAN_DELETED BOOLEAN,
    _FIVETRAN_SYNCED  TIMESTAMP_TZ(9),
    PRIMARY KEY (CTID_FIVETRAN_ID)
);

-- -----------------------------------------------------------------------------
-- Engagement Tables
-- -----------------------------------------------------------------------------

CREATE OR REPLACE TABLE RET_PROMOTIONS (
    CTID_FIVETRAN_ID       VARCHAR(16777216) NOT NULL,
    ID                     NUMBER(38,0),
    NAME                   VARCHAR(100),
    DESCRIPTION            VARCHAR(500),
    DISCOUNT_TYPE          VARCHAR(10),
    DISCOUNT_VALUE         NUMBER(10,2),
    MIN_ORDER_AMOUNT       NUMBER(10,2),
    APPLICABLE_CATEGORY_ID NUMBER(38,0),
    START_DATE             DATE,
    END_DATE               DATE,
    IS_ACTIVE              BOOLEAN,
    CREATED_AT             TIMESTAMP_NTZ(9),
    _FIVETRAN_DELETED      BOOLEAN,
    _FIVETRAN_SYNCED       TIMESTAMP_TZ(9),
    PRIMARY KEY (CTID_FIVETRAN_ID)
);

CREATE OR REPLACE TABLE RET_TICKETS (
    CTID_FIVETRAN_ID  VARCHAR(16777216) NOT NULL,
    ID                NUMBER(38,0),
    CUSTOMER_ID       NUMBER(38,0),
    ORDER_ID          NUMBER(38,0),
    ISSUE_TYPE        VARCHAR(30),
    PRIORITY          VARCHAR(10),
    STATUS            VARCHAR(20),
    DESCRIPTION       VARCHAR(1000),
    CREATED_AT        TIMESTAMP_NTZ(9),
    RESOLVED_AT       TIMESTAMP_NTZ(9),
    _FIVETRAN_DELETED BOOLEAN,
    _FIVETRAN_SYNCED  TIMESTAMP_TZ(9),
    PRIMARY KEY (CTID_FIVETRAN_ID)
);

CREATE OR REPLACE TABLE RET_PRODUCT_REVIEWS (
    CTID_FIVETRAN_ID    VARCHAR(16777216) NOT NULL,
    ID                  NUMBER(38,0),
    PRODUCT_ID          NUMBER(38,0),
    CUSTOMER_ID         NUMBER(38,0),
    RATING              NUMBER(1,0),
    REVIEW_TITLE        VARCHAR(200),
    REVIEW_TEXT         VARCHAR(2000),
    IS_VERIFIED_PURCHASE BOOLEAN,
    CREATED_AT          TIMESTAMP_NTZ(9),
    _FIVETRAN_DELETED   BOOLEAN,
    _FIVETRAN_SYNCED    TIMESTAMP_TZ(9),
    PRIMARY KEY (CTID_FIVETRAN_ID)
);


-- #############################################################################
-- FOREIGN KEY CONSTRAINTS (NOT ENFORCED)
-- Snowflake does not enforce FKs, but they document relationships and are
-- used by dbt relationship tests and BI tool join inference.
-- #############################################################################

-- Products → Subcategories → Categories
ALTER TABLE RET_PRODUCT_SUBCATEGORIES ADD CONSTRAINT FK_SUBCATEGORIES_CATEGORY
    FOREIGN KEY (CATEGORY_ID) REFERENCES RET_PRODUCT_CATEGORIES(ID) NOT ENFORCED;

ALTER TABLE RET_PRODUCTS ADD CONSTRAINT FK_PRODUCTS_SUBCATEGORY
    FOREIGN KEY (SUBCATEGORY_ID) REFERENCES RET_PRODUCT_SUBCATEGORIES(ID) NOT ENFORCED;

-- Products → Vendors
ALTER TABLE RET_PRODUCTS ADD CONSTRAINT FK_PRODUCTS_VENDOR
    FOREIGN KEY (VENDOR_ID) REFERENCES RET_VENDORS(ID) NOT ENFORCED;

-- Orders → Customers, Warehouses
ALTER TABLE RET_ORDERS ADD CONSTRAINT FK_ORDERS_CUSTOMER
    FOREIGN KEY (CUSTOMER_ID) REFERENCES RET_CUSTOMERS(ID) NOT ENFORCED;

ALTER TABLE RET_ORDERS ADD CONSTRAINT FK_ORDERS_WAREHOUSE
    FOREIGN KEY (WAREHOUSE_ID) REFERENCES RET_WAREHOUSES(ID) NOT ENFORCED;

-- Order Items → Orders, Products
ALTER TABLE RET_ORDER_ITEMS ADD CONSTRAINT FK_ORDER_ITEMS_ORDER
    FOREIGN KEY (ORDER_ID) REFERENCES RET_ORDERS(ID) NOT ENFORCED;

ALTER TABLE RET_ORDER_ITEMS ADD CONSTRAINT FK_ORDER_ITEMS_PRODUCT
    FOREIGN KEY (PRODUCT_ID) REFERENCES RET_PRODUCTS(ID) NOT ENFORCED;

-- Returns → Orders, Order Items, Products, Customers
ALTER TABLE RET_RETURNS ADD CONSTRAINT FK_RETURNS_ORDER
    FOREIGN KEY (ORDER_ID) REFERENCES RET_ORDERS(ID) NOT ENFORCED;

ALTER TABLE RET_RETURNS ADD CONSTRAINT FK_RETURNS_ORDER_ITEM
    FOREIGN KEY (ORDER_ITEM_ID) REFERENCES RET_ORDER_ITEMS(ID) NOT ENFORCED;

ALTER TABLE RET_RETURNS ADD CONSTRAINT FK_RETURNS_PRODUCT
    FOREIGN KEY (PRODUCT_ID) REFERENCES RET_PRODUCTS(ID) NOT ENFORCED;

ALTER TABLE RET_RETURNS ADD CONSTRAINT FK_RETURNS_CUSTOMER
    FOREIGN KEY (CUSTOMER_ID) REFERENCES RET_CUSTOMERS(ID) NOT ENFORCED;

-- Shipments → Warehouses; Shipment Lines → Shipments, Products
ALTER TABLE RET_SHIPMENTS ADD CONSTRAINT FK_SHIPMENTS_DEST_WAREHOUSE
    FOREIGN KEY (DESTINATION_WAREHOUSE_ID) REFERENCES RET_WAREHOUSES(ID) NOT ENFORCED;

ALTER TABLE RET_SHIPMENT_LINES ADD CONSTRAINT FK_SHIPMENT_LINES_SHIPMENT
    FOREIGN KEY (SHIPMENT_ID) REFERENCES RET_SHIPMENTS(ID) NOT ENFORCED;

ALTER TABLE RET_SHIPMENT_LINES ADD CONSTRAINT FK_SHIPMENT_LINES_PRODUCT
    FOREIGN KEY (PRODUCT_ID) REFERENCES RET_PRODUCTS(ID) NOT ENFORCED;

-- Inventory → Products, Warehouses
ALTER TABLE RET_INVENTORY ADD CONSTRAINT FK_INVENTORY_PRODUCT
    FOREIGN KEY (PRODUCT_ID) REFERENCES RET_PRODUCTS(ID) NOT ENFORCED;

ALTER TABLE RET_INVENTORY ADD CONSTRAINT FK_INVENTORY_WAREHOUSE
    FOREIGN KEY (WAREHOUSE_ID) REFERENCES RET_WAREHOUSES(ID) NOT ENFORCED;

-- Tickets → Customers, Orders
ALTER TABLE RET_TICKETS ADD CONSTRAINT FK_TICKETS_CUSTOMER
    FOREIGN KEY (CUSTOMER_ID) REFERENCES RET_CUSTOMERS(ID) NOT ENFORCED;

ALTER TABLE RET_TICKETS ADD CONSTRAINT FK_TICKETS_ORDER
    FOREIGN KEY (ORDER_ID) REFERENCES RET_ORDERS(ID) NOT ENFORCED;

-- Promotions → Categories
ALTER TABLE RET_PROMOTIONS ADD CONSTRAINT FK_PROMOTIONS_CATEGORY
    FOREIGN KEY (APPLICABLE_CATEGORY_ID) REFERENCES RET_PRODUCT_CATEGORIES(ID) NOT ENFORCED;

-- Reviews → Products, Customers
ALTER TABLE RET_PRODUCT_REVIEWS ADD CONSTRAINT FK_REVIEWS_PRODUCT
    FOREIGN KEY (PRODUCT_ID) REFERENCES RET_PRODUCTS(ID) NOT ENFORCED;

ALTER TABLE RET_PRODUCT_REVIEWS ADD CONSTRAINT FK_REVIEWS_CUSTOMER
    FOREIGN KEY (CUSTOMER_ID) REFERENCES RET_CUSTOMERS(ID) NOT ENFORCED;
