-- DDL export for Snowflake schema SNOWFLAKE_SUMMIT_2026_HOL_DB.SF_HOL_2026_RETAIL
-- Generated from get_ddl('schema', current_database() || '.SF_HOL_2026_RETAIL', true) via dbt show.

create or replace schema SNOWFLAKE_SUMMIT_2026_HOL_DB.SF_HOL_2026_RETAIL;

create or replace TABLE SNOWFLAKE_SUMMIT_2026_HOL_DB.SF_HOL_2026_RETAIL.RET_CUSTOMERS (
	CTID_FIVETRAN_ID VARCHAR(16) NOT NULL,
	ID NUMBER(38,0),
	FIRST_NAME VARCHAR(100),
	LAST_NAME VARCHAR(100),
	EMAIL VARCHAR(300),
	PHONE VARCHAR(20),
	ADDRESS VARCHAR(200),
	CITY VARCHAR(100),
	STATE VARCHAR(2),
	ZIP VARCHAR(10),
	REGION VARCHAR(50),
	CUSTOMER_TYPE VARCHAR(20),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	_FIVETRAN_DELETED BOOLEAN,
	_FIVETRAN_SYNCED TIMESTAMP_TZ(9),
	primary key (CTID_FIVETRAN_ID)
);
create or replace TABLE SNOWFLAKE_SUMMIT_2026_HOL_DB.SF_HOL_2026_RETAIL.RET_INVENTORY (
	CTID_FIVETRAN_ID VARCHAR(16) NOT NULL,
	ID NUMBER(38,0),
	PRODUCT_ID NUMBER(38,0),
	WAREHOUSE_ID NUMBER(38,0),
	QUANTITY_ON_HAND NUMBER(10,0),
	REORDER_POINT NUMBER(10,0),
	REORDER_QUANTITY NUMBER(10,0),
	LAST_RESTOCKED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	_FIVETRAN_DELETED BOOLEAN,
	_FIVETRAN_SYNCED TIMESTAMP_TZ(9),
	primary key (CTID_FIVETRAN_ID)
);
create or replace TABLE SNOWFLAKE_SUMMIT_2026_HOL_DB.SF_HOL_2026_RETAIL.RET_INVENTORY_TRANSACTIONS (
	CTID_FIVETRAN_ID VARCHAR(16) NOT NULL,
	ID NUMBER(38,0),
	PRODUCT_ID NUMBER(38,0),
	WAREHOUSE_ID NUMBER(38,0),
	TRANSACTION_TYPE VARCHAR(20),
	QUANTITY NUMBER(10,0),
	REFERENCE_ID NUMBER(38,0),
	NOTES VARCHAR(500),
	CREATED_AT TIMESTAMP_NTZ(9),
	_FIVETRAN_DELETED BOOLEAN,
	_FIVETRAN_SYNCED TIMESTAMP_TZ(9),
	primary key (CTID_FIVETRAN_ID)
);
create or replace TABLE SNOWFLAKE_SUMMIT_2026_HOL_DB.SF_HOL_2026_RETAIL.RET_ORDERS (
	CTID_FIVETRAN_ID VARCHAR(16) NOT NULL,
	ID NUMBER(38,0),
	CUSTOMER_ID NUMBER(38,0),
	ORDER_DATE TIMESTAMP_NTZ(9),
	STATUS VARCHAR(20),
	SHIPPING_METHOD VARCHAR(30),
	SHIPPING_ADDRESS VARCHAR(200),
	SHIPPING_CITY VARCHAR(100),
	SHIPPING_STATE VARCHAR(2),
	SHIPPING_ZIP VARCHAR(10),
	SUBTOTAL NUMBER(10,2),
	TAX_AMOUNT NUMBER(10,2),
	SHIPPING_COST NUMBER(10,2),
	TOTAL_AMOUNT NUMBER(10,2),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	_FIVETRAN_DELETED BOOLEAN,
	_FIVETRAN_SYNCED TIMESTAMP_TZ(9),
	primary key (CTID_FIVETRAN_ID)
);
create or replace TABLE SNOWFLAKE_SUMMIT_2026_HOL_DB.SF_HOL_2026_RETAIL.RET_ORDER_ITEMS (
	CTID_FIVETRAN_ID VARCHAR(16) NOT NULL,
	ID NUMBER(38,0),
	ORDER_ID NUMBER(38,0),
	PRODUCT_ID NUMBER(38,0),
	QUANTITY NUMBER(10,0),
	UNIT_PRICE NUMBER(10,2),
	DISCOUNT_PCT NUMBER(5,2),
	LINE_TOTAL NUMBER(10,2),
	CREATED_AT TIMESTAMP_NTZ(9),
	_FIVETRAN_DELETED BOOLEAN,
	_FIVETRAN_SYNCED TIMESTAMP_TZ(9),
	primary key (CTID_FIVETRAN_ID)
);
create or replace TABLE SNOWFLAKE_SUMMIT_2026_HOL_DB.SF_HOL_2026_RETAIL.RET_PRODUCTS (
	CTID_FIVETRAN_ID VARCHAR(16) NOT NULL,
	ID NUMBER(38,0),
	SKU VARCHAR(20),
	NAME VARCHAR(200),
	DESCRIPTION VARCHAR(1000),
	SUBCATEGORY_ID NUMBER(38,0),
	BRAND VARCHAR(100),
	UNIT_PRICE NUMBER(10,2),
	WEIGHT_LBS NUMBER(8,2),
	IS_ACTIVE BOOLEAN,
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	_FIVETRAN_DELETED BOOLEAN,
	_FIVETRAN_SYNCED TIMESTAMP_TZ(9),
	primary key (CTID_FIVETRAN_ID)
);
create or replace TABLE SNOWFLAKE_SUMMIT_2026_HOL_DB.SF_HOL_2026_RETAIL.RET_PRODUCT_CATEGORIES (
	CTID_FIVETRAN_ID VARCHAR(16) NOT NULL,
	ID NUMBER(38,0),
	NAME VARCHAR(100),
	DESCRIPTION VARCHAR(500),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	_FIVETRAN_DELETED BOOLEAN,
	_FIVETRAN_SYNCED TIMESTAMP_TZ(9),
	primary key (CTID_FIVETRAN_ID)
);
create or replace TABLE SNOWFLAKE_SUMMIT_2026_HOL_DB.SF_HOL_2026_RETAIL.RET_PRODUCT_REVIEWS (
	CTID_FIVETRAN_ID VARCHAR(16) NOT NULL,
	ID NUMBER(38,0),
	PRODUCT_ID NUMBER(38,0),
	CUSTOMER_ID NUMBER(38,0),
	RATING NUMBER(1,0),
	REVIEW_TITLE VARCHAR(200),
	REVIEW_TEXT VARCHAR(2000),
	IS_VERIFIED_PURCHASE BOOLEAN,
	CREATED_AT TIMESTAMP_NTZ(9),
	_FIVETRAN_DELETED BOOLEAN,
	_FIVETRAN_SYNCED TIMESTAMP_TZ(9),
	primary key (CTID_FIVETRAN_ID)
);
create or replace TABLE SNOWFLAKE_SUMMIT_2026_HOL_DB.SF_HOL_2026_RETAIL.RET_PRODUCT_SUBCATEGORIES (
	CTID_FIVETRAN_ID VARCHAR(16) NOT NULL,
	ID NUMBER(38,0),
	CATEGORY_ID NUMBER(38,0),
	NAME VARCHAR(100),
	DESCRIPTION VARCHAR(500),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	_FIVETRAN_DELETED BOOLEAN,
	_FIVETRAN_SYNCED TIMESTAMP_TZ(9),
	primary key (CTID_FIVETRAN_ID)
);
create or replace TABLE SNOWFLAKE_SUMMIT_2026_HOL_DB.SF_HOL_2026_RETAIL.RET_PROMOTIONS (
	CTID_FIVETRAN_ID VARCHAR(16) NOT NULL,
	ID NUMBER(38,0),
	NAME VARCHAR(100),
	DESCRIPTION VARCHAR(500),
	DISCOUNT_TYPE VARCHAR(10),
	DISCOUNT_VALUE NUMBER(10,2),
	MIN_ORDER_AMOUNT NUMBER(10,2),
	APPLICABLE_CATEGORY_ID NUMBER(38,0),
	START_DATE DATE,
	END_DATE DATE,
	IS_ACTIVE BOOLEAN,
	CREATED_AT TIMESTAMP_NTZ(9),
	_FIVETRAN_DELETED BOOLEAN,
	_FIVETRAN_SYNCED TIMESTAMP_TZ(9),
	primary key (CTID_FIVETRAN_ID)
);
create or replace TABLE SNOWFLAKE_SUMMIT_2026_HOL_DB.SF_HOL_2026_RETAIL.RET_TICKETS (
	CTID_FIVETRAN_ID VARCHAR(16) NOT NULL,
	ID NUMBER(38,0),
	CUSTOMER_ID NUMBER(38,0),
	ORDER_ID NUMBER(38,0),
	ISSUE_TYPE VARCHAR(30),
	PRIORITY VARCHAR(10),
	STATUS VARCHAR(20),
	DESCRIPTION VARCHAR(1000),
	CREATED_AT TIMESTAMP_NTZ(9),
	RESOLVED_AT TIMESTAMP_NTZ(9),
	_FIVETRAN_DELETED BOOLEAN,
	_FIVETRAN_SYNCED TIMESTAMP_TZ(9),
	primary key (CTID_FIVETRAN_ID)
);
create or replace TABLE SNOWFLAKE_SUMMIT_2026_HOL_DB.SF_HOL_2026_RETAIL.RET_WAREHOUSES (
	CTID_FIVETRAN_ID VARCHAR(16) NOT NULL,
	ID NUMBER(38,0),
	NAME VARCHAR(100),
	ADDRESS VARCHAR(200),
	CITY VARCHAR(100),
	STATE VARCHAR(2),
	ZIP VARCHAR(10),
	CAPACITY_SQFT NUMBER(10,0),
	IS_ACTIVE BOOLEAN,
	CREATED_AT TIMESTAMP_NTZ(9),
	_FIVETRAN_DELETED BOOLEAN,
	_FIVETRAN_SYNCED TIMESTAMP_TZ(9),
	primary key (CTID_FIVETRAN_ID)
);
